"""create_service_tables

Revision ID: 15b1747fd7a4
Revises: 82a042eab766
Create Date: 2026-08-13 09:44:55.512700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15b1747fd7a4'
down_revision: Union[str, None] = '82a042eab766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['service_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_categories_id'), 'service_categories', ['id'], unique=False)
    op.create_index(op.f('ix_service_categories_name'), 'service_categories', ['name'], unique=True)
    op.create_index(op.f('ix_service_categories_parent_id'), 'service_categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_service_categories_slug'), 'service_categories', ['slug'], unique=True)
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freelancer_profile_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('short_description', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('service_type', sa.Enum('ON_SITE', 'REMOTE', 'HYBRID', name='servicetype'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('starting_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('delivery_time_days', sa.Integer(), nullable=True),
    sa.Column('revisions', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'PAUSED', 'ARCHIVED', name='servicestatus'), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('service_radius_km', sa.Integer(), nullable=True),
    sa.Column('travel_available', sa.Boolean(), nullable=False),
    sa.Column('travel_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['freelancer_profile_id'], ['freelancer_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['service_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_category_id'), 'services', ['category_id'], unique=False)
    op.create_index(op.f('ix_services_freelancer_profile_id'), 'services', ['freelancer_profile_id'], unique=False)
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_services_service_type'), 'services', ['service_type'], unique=False)
    op.create_index(op.f('ix_services_slug'), 'services', ['slug'], unique=True)
    op.create_index(op.f('ix_services_status'), 'services', ['status'], unique=False)
    op.create_index(op.f('ix_services_subcategory_id'), 'services', ['subcategory_id'], unique=False)
    op.create_table('service_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', 'EXTERNAL_VIDEO', name='mediatype'), nullable=False),
    sa.Column('media_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_media_id'), 'service_media', ['id'], unique=False)
    op.create_index(op.f('ix_service_media_service_id'), 'service_media', ['service_id'], unique=False)
    op.create_table('service_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('package_type', sa.Enum('BASIC', 'STANDARD', 'PREMIUM', name='packagetype'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_time_days', sa.Integer(), nullable=False),
    sa.Column('revisions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_packages_id'), 'service_packages', ['id'], unique=False)
    op.create_index(op.f('ix_service_packages_service_id'), 'service_packages', ['service_id'], unique=False)
    op.create_table('service_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('field_type', sa.Enum('TEXT', 'TEXTAREA', 'NUMBER', 'DATE', 'SELECT', 'BOOLEAN', 'FILE', name='requirementfieldtype'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_requirements_id'), 'service_requirements', ['id'], unique=False)
    op.create_index(op.f('ix_service_requirements_service_id'), 'service_requirements', ['service_id'], unique=False)
    op.create_table('package_deliverables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_package_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_package_id'], ['service_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_deliverables_id'), 'package_deliverables', ['id'], unique=False)
    op.create_index(op.f('ix_package_deliverables_service_package_id'), 'package_deliverables', ['service_package_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_package_deliverables_service_package_id'), table_name='package_deliverables')
    op.drop_index(op.f('ix_package_deliverables_id'), table_name='package_deliverables')
    op.drop_table('package_deliverables')
    op.drop_index(op.f('ix_service_requirements_service_id'), table_name='service_requirements')
    op.drop_index(op.f('ix_service_requirements_id'), table_name='service_requirements')
    op.drop_table('service_requirements')
    op.drop_index(op.f('ix_service_packages_service_id'), table_name='service_packages')
    op.drop_index(op.f('ix_service_packages_id'), table_name='service_packages')
    op.drop_table('service_packages')
    op.drop_index(op.f('ix_service_media_service_id'), table_name='service_media')
    op.drop_index(op.f('ix_service_media_id'), table_name='service_media')
    op.drop_table('service_media')
    op.drop_index(op.f('ix_services_subcategory_id'), table_name='services')
    op.drop_index(op.f('ix_services_status'), table_name='services')
    op.drop_index(op.f('ix_services_slug'), table_name='services')
    op.drop_index(op.f('ix_services_service_type'), table_name='services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_index(op.f('ix_services_freelancer_profile_id'), table_name='services')
    op.drop_index(op.f('ix_services_category_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_service_categories_slug'), table_name='service_categories')
    op.drop_index(op.f('ix_service_categories_parent_id'), table_name='service_categories')
    op.drop_index(op.f('ix_service_categories_name'), table_name='service_categories')
    op.drop_index(op.f('ix_service_categories_id'), table_name='service_categories')
    op.drop_table('service_categories')
    # ### end Alembic commands ###
