"""add_missing_indexes_phase_12

Revision ID: 7971c608bf71
Revises: f4d94192cf2d
Create Date: 2026-08-14 14:24:28.474929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7971c608bf71'
down_revision: Union[str, None] = 'f4d94192cf2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_freelancer_profiles_city'), 'freelancer_profiles', ['city'], unique=False)
    op.create_index(op.f('ix_freelancer_profiles_primary_profession'), 'freelancer_profiles', ['primary_profession'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_freelancer_profiles_primary_profession'), table_name='freelancer_profiles')
    op.drop_index(op.f('ix_freelancer_profiles_city'), table_name='freelancer_profiles')
    # ### end Alembic commands ###
