"""create_freelancer_tables

Revision ID: 82a042eab766
Revises: 2d33aa8f0862
Create Date: 2026-08-13 09:17:00.114413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82a042eab766'
down_revision: Union[str, None] = '2d33aa8f0862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('freelancer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('professional_title', sa.String(length=120), nullable=False),
    sa.Column('primary_profession', sa.Enum('PHOTOGRAPHER', 'VIDEOGRAPHER', 'VIDEO_EDITOR', 'PHOTO_EDITOR', 'CINEMATOGRAPHER', 'DRONE_OPERATOR', 'REEL_EDITOR', 'MOTION_GRAPHICS_ARTIST', 'COLOR_GRADER', 'OTHER', name='freelancerprofession'), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('service_radius_km', sa.Integer(), nullable=True),
    sa.Column('willing_to_travel', sa.Boolean(), nullable=False),
    sa.Column('starting_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('event_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profile_photo_url', sa.String(length=500), nullable=True),
    sa.Column('cover_photo_url', sa.String(length=500), nullable=True),
    sa.Column('profile_completion_percentage', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.Enum('NOT_SUBMITTED', 'PENDING', 'VERIFIED', 'REJECTED', name='verificationstatus'), nullable=False),
    sa.Column('is_profile_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freelancer_profiles_id'), 'freelancer_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_freelancer_profiles_user_id'), 'freelancer_profiles', ['user_id'], unique=True)
    op.create_table('freelancer_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freelancer_profile_id', sa.Integer(), nullable=False),
    sa.Column('equipment_type', sa.Enum('CAMERA', 'LENS', 'DRONE', 'GIMBAL', 'LIGHTING', 'MICROPHONE', 'TRIPOD', 'COMPUTER', 'OTHER', name='equipmenttype'), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['freelancer_profile_id'], ['freelancer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freelancer_equipment_freelancer_profile_id'), 'freelancer_equipment', ['freelancer_profile_id'], unique=False)
    op.create_index(op.f('ix_freelancer_equipment_id'), 'freelancer_equipment', ['id'], unique=False)
    op.create_table('freelancer_skills',
    sa.Column('freelancer_profile_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['freelancer_profile_id'], ['freelancer_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('freelancer_profile_id', 'skill_id')
    )
    op.create_table('portfolio_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freelancer_profile_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', 'EXTERNAL_VIDEO', name='mediatype'), nullable=False),
    sa.Column('media_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('project_date', sa.Date(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['freelancer_profile_id'], ['freelancer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_items_freelancer_profile_id'), 'portfolio_items', ['freelancer_profile_id'], unique=False)
    op.create_index(op.f('ix_portfolio_items_id'), 'portfolio_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_items_id'), table_name='portfolio_items')
    op.drop_index(op.f('ix_portfolio_items_freelancer_profile_id'), table_name='portfolio_items')
    op.drop_table('portfolio_items')
    op.drop_table('freelancer_skills')
    op.drop_index(op.f('ix_freelancer_equipment_id'), table_name='freelancer_equipment')
    op.drop_index(op.f('ix_freelancer_equipment_freelancer_profile_id'), table_name='freelancer_equipment')
    op.drop_table('freelancer_equipment')
    op.drop_index(op.f('ix_freelancer_profiles_user_id'), table_name='freelancer_profiles')
    op.drop_index(op.f('ix_freelancer_profiles_id'), table_name='freelancer_profiles')
    op.drop_table('freelancer_profiles')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
