"""create_phase_9_tables

Revision ID: 92c5923f87ab
Revises: 9cb93f1ae23d
Create Date: 2026-08-14 12:56:34.889721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '92c5923f87ab'
down_revision: Union[str, None] = '9cb93f1ae23d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trust_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trust_badges_code'), 'trust_badges', ['code'], unique=True)
    op.create_index(op.f('ix_trust_badges_id'), 'trust_badges', ['id'], unique=False)
    op.create_table('favourite_freelancers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('freelancer_profile_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['freelancer_profile_id'], ['freelancer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'freelancer_profile_id', name='uq_client_freelancer_favourite')
    )
    op.create_index(op.f('ix_favourite_freelancers_client_id'), 'favourite_freelancers', ['client_id'], unique=False)
    op.create_index(op.f('ix_favourite_freelancers_freelancer_profile_id'), 'favourite_freelancers', ['freelancer_profile_id'], unique=False)
    op.create_index(op.f('ix_favourite_freelancers_id'), 'favourite_freelancers', ['id'], unique=False)
    op.create_table('freelancer_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freelancer_profile_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['trust_badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['freelancer_profile_id'], ['freelancer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('freelancer_profile_id', 'badge_id', name='uq_freelancer_badge')
    )
    op.create_index(op.f('ix_freelancer_badges_badge_id'), 'freelancer_badges', ['badge_id'], unique=False)
    op.create_index(op.f('ix_freelancer_badges_freelancer_profile_id'), 'freelancer_badges', ['freelancer_profile_id'], unique=False)
    op.create_index(op.f('ix_freelancer_badges_id'), 'freelancer_badges', ['id'], unique=False)
    op.create_table('favourite_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'service_id', name='uq_client_service_favourite')
    )
    op.create_index(op.f('ix_favourite_services_client_id'), 'favourite_services', ['client_id'], unique=False)
    op.create_index(op.f('ix_favourite_services_id'), 'favourite_services', ['id'], unique=False)
    op.create_index(op.f('ix_favourite_services_service_id'), 'favourite_services', ['service_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('freelancer_profile_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('overall_rating', sa.Integer(), nullable=False),
    sa.Column('quality_rating', sa.Integer(), nullable=True),
    sa.Column('communication_rating', sa.Integer(), nullable=True),
    sa.Column('professionalism_rating', sa.Integer(), nullable=True),
    sa.Column('timeliness_rating', sa.Integer(), nullable=True),
    sa.Column('value_rating', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PUBLISHED', 'HIDDEN', 'REPORTED', 'REMOVED', name='reviewstatus'), nullable=False),
    sa.Column('is_verified_booking', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['freelancer_profile_id'], ['freelancer_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_booking_id'), 'reviews', ['booking_id'], unique=True)
    op.create_index(op.f('ix_reviews_client_id'), 'reviews', ['client_id'], unique=False)
    op.create_index(op.f('ix_reviews_created_at'), 'reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviews_freelancer_profile_id'), 'reviews', ['freelancer_profile_id'], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_overall_rating'), 'reviews', ['overall_rating'], unique=False)
    op.create_index(op.f('ix_reviews_project_id'), 'reviews', ['project_id'], unique=False)
    op.create_index(op.f('ix_reviews_service_id'), 'reviews', ['service_id'], unique=False)
    op.create_index(op.f('ix_reviews_status'), 'reviews', ['status'], unique=False)
    op.create_table('review_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('reported_by_user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('HARASSMENT', 'SPAM', 'FALSE_INFORMATION', 'PERSONAL_INFORMATION', 'ABUSIVE_LANGUAGE', 'OTHER', name='reportreason'), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'RESOLVED', 'DISMISSED', name='reportstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_reports_id'), 'review_reports', ['id'], unique=False)
    op.create_index(op.f('ix_review_reports_reported_by_user_id'), 'review_reports', ['reported_by_user_id'], unique=False)
    op.create_index(op.f('ix_review_reports_review_id'), 'review_reports', ['review_id'], unique=False)
    op.create_index(op.f('ix_review_reports_status'), 'review_reports', ['status'], unique=False)
    op.create_table('review_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('freelancer_profile_id', sa.Integer(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['freelancer_profile_id'], ['freelancer_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_responses_freelancer_profile_id'), 'review_responses', ['freelancer_profile_id'], unique=False)
    op.create_index(op.f('ix_review_responses_id'), 'review_responses', ['id'], unique=False)
    op.create_index(op.f('ix_review_responses_review_id'), 'review_responses', ['review_id'], unique=True)
    op.create_index(op.f('ix_booking_requirement_answers_service_requirement_id'), 'booking_requirement_answers', ['service_requirement_id'], unique=False)
    op.alter_column('booking_reschedule_requests', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', name='reschedulerequeststatus'),
               existing_nullable=False)
    op.create_index(op.f('ix_booking_reschedule_requests_status'), 'booking_reschedule_requests', ['status'], unique=False)
    op.alter_column('bookings', 'booking_number',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('bookings', 'source_type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('SERVICE', 'PROJECT', name='bookingsourcetype'),
               nullable=False)
    op.alter_column('bookings', 'booking_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('bookings', 'status',
               existing_type=mysql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', 'CANCELLED'),
               type_=sa.Enum('REQUESTED', 'PENDING_CONFIRMATION', 'CONFIRMED', 'IN_PROGRESS', 'DELIVERY_PENDING', 'COMPLETED', 'REJECTED', 'CANCELLED', 'RESCHEDULE_REQUESTED', name='bookingstatus'),
               existing_nullable=False)
    op.alter_column('bookings', 'booking_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('bookings', 'timezone',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('bookings', 'agreed_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.alter_column('bookings', 'currency',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.create_index(op.f('ix_bookings_proposal_id'), 'bookings', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_bookings_source_type'), 'bookings', ['source_type'], unique=False)
    op.alter_column('freelancer_availabilities', 'availability_type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('AVAILABLE', 'UNAVAILABLE', 'BLOCKED', name='availabilitytype'),
               existing_nullable=False)
    op.create_index(op.f('ix_freelancer_availabilities_availability_type'), 'freelancer_availabilities', ['availability_type'], unique=False)
    op.add_column('freelancer_profiles', sa.Column('average_rating', sa.Float(), nullable=True))
    op.add_column('freelancer_profiles', sa.Column('review_count', sa.Integer(), nullable=False))
    op.add_column('freelancer_profiles', sa.Column('completed_jobs_count', sa.Integer(), nullable=False))
    op.add_column('services', sa.Column('average_rating', sa.Float(), nullable=True))
    op.add_column('services', sa.Column('review_count', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('is_phone_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_phone_verified')
    op.drop_column('services', 'review_count')
    op.drop_column('services', 'average_rating')
    op.drop_column('freelancer_profiles', 'completed_jobs_count')
    op.drop_column('freelancer_profiles', 'review_count')
    op.drop_column('freelancer_profiles', 'average_rating')
    op.drop_index(op.f('ix_freelancer_availabilities_availability_type'), table_name='freelancer_availabilities')
    op.alter_column('freelancer_availabilities', 'availability_type',
               existing_type=sa.Enum('AVAILABLE', 'UNAVAILABLE', 'BLOCKED', name='availabilitytype'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_bookings_source_type'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_proposal_id'), table_name='bookings')
    op.alter_column('bookings', 'currency',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('bookings', 'agreed_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('bookings', 'timezone',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('bookings', 'booking_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('bookings', 'status',
               existing_type=sa.Enum('REQUESTED', 'PENDING_CONFIRMATION', 'CONFIRMED', 'IN_PROGRESS', 'DELIVERY_PENDING', 'COMPLETED', 'REJECTED', 'CANCELLED', 'RESCHEDULE_REQUESTED', name='bookingstatus'),
               type_=mysql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', 'CANCELLED'),
               existing_nullable=False)
    op.alter_column('bookings', 'booking_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('bookings', 'source_type',
               existing_type=sa.Enum('SERVICE', 'PROJECT', name='bookingsourcetype'),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('bookings', 'booking_number',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_booking_reschedule_requests_status'), table_name='booking_reschedule_requests')
    op.alter_column('booking_reschedule_requests', 'status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', name='reschedulerequeststatus'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_booking_requirement_answers_service_requirement_id'), table_name='booking_requirement_answers')
    op.drop_index(op.f('ix_review_responses_review_id'), table_name='review_responses')
    op.drop_index(op.f('ix_review_responses_id'), table_name='review_responses')
    op.drop_index(op.f('ix_review_responses_freelancer_profile_id'), table_name='review_responses')
    op.drop_table('review_responses')
    op.drop_index(op.f('ix_review_reports_status'), table_name='review_reports')
    op.drop_index(op.f('ix_review_reports_review_id'), table_name='review_reports')
    op.drop_index(op.f('ix_review_reports_reported_by_user_id'), table_name='review_reports')
    op.drop_index(op.f('ix_review_reports_id'), table_name='review_reports')
    op.drop_table('review_reports')
    op.drop_index(op.f('ix_reviews_status'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_service_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_project_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_overall_rating'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_freelancer_profile_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_created_at'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_client_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_booking_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_favourite_services_service_id'), table_name='favourite_services')
    op.drop_index(op.f('ix_favourite_services_id'), table_name='favourite_services')
    op.drop_index(op.f('ix_favourite_services_client_id'), table_name='favourite_services')
    op.drop_table('favourite_services')
    op.drop_index(op.f('ix_freelancer_badges_id'), table_name='freelancer_badges')
    op.drop_index(op.f('ix_freelancer_badges_freelancer_profile_id'), table_name='freelancer_badges')
    op.drop_index(op.f('ix_freelancer_badges_badge_id'), table_name='freelancer_badges')
    op.drop_table('freelancer_badges')
    op.drop_index(op.f('ix_favourite_freelancers_id'), table_name='favourite_freelancers')
    op.drop_index(op.f('ix_favourite_freelancers_freelancer_profile_id'), table_name='favourite_freelancers')
    op.drop_index(op.f('ix_favourite_freelancers_client_id'), table_name='favourite_freelancers')
    op.drop_table('favourite_freelancers')
    op.drop_index(op.f('ix_trust_badges_id'), table_name='trust_badges')
    op.drop_index(op.f('ix_trust_badges_code'), table_name='trust_badges')
    op.drop_table('trust_badges')
    # ### end Alembic commands ###
