"""add_login_id_to_users

Revision ID: b7fec4d7cf69
Revises: 7971c608bf71
Create Date: 2026-08-14 09:34:43.653782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7fec4d7cf69'
down_revision: Union[str, None] = '7971c608bf71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_users_login_id'), 'users', ['login_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_login_id'), table_name='users')
    op.drop_column('users', 'login_id')
    # ### end Alembic commands ###
