"""make profile fields nullable and add social links

Revision ID: b98ac40aed0c
Revises: 5cd117098c69
Create Date: 2026-08-18 07:01:21.859734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b98ac40aed0c'
down_revision: Union[str, None] = '5cd117098c69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freelancer_profiles', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('freelancer_profiles', sa.Column('instagram', sa.String(length=500), nullable=True))
    op.add_column('freelancer_profiles', sa.Column('behance', sa.String(length=500), nullable=True))
    op.alter_column('freelancer_profiles', 'professional_title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120),
               nullable=True)
    op.alter_column('freelancer_profiles', 'bio',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.alter_column('freelancer_profiles', 'experience_years',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('freelancer_profiles', 'city',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    op.alter_column('freelancer_profiles', 'state',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    op.alter_column('freelancer_profiles', 'country',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('freelancer_profiles', 'country',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.alter_column('freelancer_profiles', 'state',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.alter_column('freelancer_profiles', 'city',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.alter_column('freelancer_profiles', 'experience_years',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('freelancer_profiles', 'bio',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.alter_column('freelancer_profiles', 'professional_title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120),
               nullable=False)
    op.drop_column('freelancer_profiles', 'behance')
    op.drop_column('freelancer_profiles', 'instagram')
    op.drop_column('freelancer_profiles', 'website')
    # ### end Alembic commands ###
