"""create phase 11 tables

Revision ID: f4d94192cf2d
Revises: 74d4d8de047c
Create Date: 2026-08-14 14:03:39.782937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4d94192cf2d'
down_revision: Union[str, None] = '74d4d8de047c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_logs_action'), 'admin_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_admin_user_id'), 'admin_audit_logs', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_created_at'), 'admin_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_entity_type'), 'admin_audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_id'), 'admin_audit_logs', ['id'], unique=False)

    op.create_table('platform_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.Enum('STRING', 'INTEGER', 'DECIMAL', 'BOOLEAN', 'JSON', name='settingvaluetype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('updated_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_settings_id'), 'platform_settings', ['id'], unique=False)
    op.create_index(op.f('ix_platform_settings_key'), 'platform_settings', ['key'], unique=True)

    op.create_table('freelancer_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freelancer_profile_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NOT_SUBMITTED', 'PENDING', 'UNDER_REVIEW', 'VERIFIED', 'REJECTED', 'RESUBMISSION_REQUIRED', name='verificationstatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['freelancer_profile_id'], ['freelancer_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freelancer_verifications_freelancer_profile_id'), 'freelancer_verifications', ['freelancer_profile_id'], unique=False)
    op.create_index(op.f('ix_freelancer_verifications_id'), 'freelancer_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_freelancer_verifications_status'), 'freelancer_verifications', ['status'], unique=False)

    op.create_table('verification_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verification_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('IDENTITY_DOCUMENT', 'ADDRESS_PROOF', 'BUSINESS_DOCUMENT', 'PORTFOLIO_PROOF', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='documentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['freelancer_verifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_documents_id'), 'verification_documents', ['id'], unique=False)
    op.create_index(op.f('ix_verification_documents_verification_id'), 'verification_documents', ['verification_id'], unique=False)

    op.create_table('disputes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispute_number', sa.String(length=50), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('opened_by_user_id', sa.Integer(), nullable=False),
    sa.Column('against_user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('WORK_NOT_DELIVERED', 'QUALITY_ISSUE', 'MISSED_DEADLINE', 'PAYMENT_ISSUE', 'UNAUTHORIZED_CANCELLATION', 'FREELANCER_NO_SHOW', 'CLIENT_NO_SHOW', 'ABUSIVE_BEHAVIOR', 'COPYRIGHT_ISSUE', 'OTHER', name='disputereason'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'WAITING_FOR_CLIENT', 'WAITING_FOR_FREELANCER', 'RESOLVED', 'CLOSED', 'REJECTED', name='disputestatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='disputepriority'), nullable=False),
    sa.Column('assigned_admin_id', sa.Integer(), nullable=True),
    sa.Column('resolution_type', sa.Enum('NO_ACTION', 'FULL_REFUND', 'PARTIAL_REFUND', 'RELEASE_TO_FREELANCER', 'BOOKING_CANCELLED', 'WARNING_ISSUED', 'ACCOUNT_ACTION', 'OTHER', name='resolutiontype'), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['against_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opened_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_against_user_id'), 'disputes', ['against_user_id'], unique=False)
    op.create_index(op.f('ix_disputes_assigned_admin_id'), 'disputes', ['assigned_admin_id'], unique=False)
    op.create_index(op.f('ix_disputes_booking_id'), 'disputes', ['booking_id'], unique=False)
    op.create_index(op.f('ix_disputes_dispute_number'), 'disputes', ['dispute_number'], unique=True)
    op.create_index(op.f('ix_disputes_id'), 'disputes', ['id'], unique=False)
    op.create_index(op.f('ix_disputes_opened_by_user_id'), 'disputes', ['opened_by_user_id'], unique=False)
    op.create_index(op.f('ix_disputes_priority'), 'disputes', ['priority'], unique=False)
    op.create_index(op.f('ix_disputes_status'), 'disputes', ['status'], unique=False)

    op.create_table('dispute_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispute_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispute_evidence_dispute_id'), 'dispute_evidence', ['dispute_id'], unique=False)
    op.create_index(op.f('ix_dispute_evidence_id'), 'dispute_evidence', ['id'], unique=False)

    op.create_table('dispute_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispute_id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_internal_admin_note', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispute_messages_dispute_id'), 'dispute_messages', ['dispute_id'], unique=False)
    op.create_index(op.f('ix_dispute_messages_id'), 'dispute_messages', ['id'], unique=False)

    # Safely modify ENUM on MySQL
    op.execute("ALTER TABLE freelancer_profiles MODIFY COLUMN verification_status ENUM('NOT_SUBMITTED', 'PENDING', 'UNDER_REVIEW', 'VERIFIED', 'REJECTED', 'RESUBMISSION_REQUIRED') NOT NULL DEFAULT 'NOT_SUBMITTED'")


def downgrade() -> None:
    op.execute("ALTER TABLE freelancer_profiles MODIFY COLUMN verification_status ENUM('NOT_SUBMITTED', 'PENDING', 'VERIFIED', 'REJECTED') NOT NULL DEFAULT 'NOT_SUBMITTED'")

    op.drop_index(op.f('ix_dispute_messages_id'), table_name='dispute_messages')
    op.drop_index(op.f('ix_dispute_messages_dispute_id'), table_name='dispute_messages')
    op.drop_table('dispute_messages')
    op.drop_index(op.f('ix_dispute_evidence_id'), table_name='dispute_evidence')
    op.drop_index(op.f('ix_dispute_evidence_dispute_id'), table_name='dispute_evidence')
    op.drop_table('dispute_evidence')
    op.drop_index(op.f('ix_disputes_status'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_priority'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_opened_by_user_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_dispute_number'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_booking_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_assigned_admin_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_against_user_id'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_verification_documents_verification_id'), table_name='verification_documents')
    op.drop_index(op.f('ix_verification_documents_id'), table_name='verification_documents')
    op.drop_table('verification_documents')
    op.drop_index(op.f('ix_freelancer_verifications_status'), table_name='freelancer_verifications')
    op.drop_index(op.f('ix_freelancer_verifications_id'), table_name='freelancer_verifications')
    op.drop_index(op.f('ix_freelancer_verifications_freelancer_profile_id'), table_name='freelancer_verifications')
    op.drop_table('freelancer_verifications')
    op.drop_index(op.f('ix_platform_settings_key'), table_name='platform_settings')
    op.drop_index(op.f('ix_platform_settings_id'), table_name='platform_settings')
    op.drop_table('platform_settings')
    op.drop_index(op.f('ix_admin_audit_logs_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_entity_type'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_created_at'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_admin_user_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_action'), table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
